'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const tools=require('../js/admin-tools.js'),content=require('../js/content.js');
const state={ore:0,energy:100,medals:0,acorns:0,prestigeLevel:0,care:{trust:0},stats:{totalClicks:0,lifetimeBones:0,walksDone:0},levels:content.defaultLevels(),levelsTraining:content.defaultTrainingLevels(),levelsCards:content.defaultCardLevels(),packPaid:content.defaultPackUnlocks(),packUnlocked:content.defaultPackUnlocks(),unlockedBreeds:['lab'],unlockedYards:['sunny'],quests:[{target:10,progress:0,claimed:false},{target:20,progress:3,claimed:true}],dailyGoals:[]};
let saves=0,event=null,ended=0,busy=false,animation=null;
const api=tools.create({state,content,serialize:()=>state,render(){},persist(){saves++},checkAchievements(){},energyMax:()=>100,busy:()=>busy,startEvent:id=>event=id,startWalk:id=>{state.activeWalk={tierId:id,endsAt:Date.now()+10000}},completeWalk(){assert(state.activeWalk.endsAt<Date.now());state.activeWalk=null;ended++},selectTab(){},animation:a=>animation=a});
for(const value of [NaN,Infinity,-1,'','no',1e20])assert.throws(()=>api.command('resource',{key:'ore',value}));
assert.throws(()=>api.command('resource',{key:'__proto__',value:1}));
assert.throws(()=>api.command('resource',{key:'energy',value:101}));
api.command('resource',{key:'ore',value:'25000'});assert.equal(state.ore,25000);
api.command('resource',{key:'trust',value:100});assert.equal(state.care.trust,100);
api.command('breed',{id:'corgi'});assert.equal(state.selectedBreed,'corgi');assert(state.unlockedBreeds.includes('corgi'));
assert.throws(()=>api.command('breed',{id:'bad'}));
api.command('quests');assert.equal(state.quests[0].progress,10);assert.equal(state.quests[1].progress,3);assert.equal(state.ore,25000,'preparing quests does not award bones');
api.command('pack',{id:'crew',enabled:true});assert.equal(state.packPaid.crew,true);
api.command('entitlement',{id:'noAds',enabled:true});assert.equal(state.noAds,true);
assert.throws(()=>api.command('level',{group:'levelsCards',id:content.SKILL_CARDS[0].id,value:999}));
api.command('unlock');assert.deepEqual(state.stickers,content.STICKERS.map(x=>x.id));
api.command('walk',{id:content.WALK_TIERS[0].id,style:'trail'});
assert.throws(()=>api.command('event',{id:'toy'}));api.command('finishWalk');assert.equal(ended,1);
assert.throws(()=>api.command('finishWalk'));busy=true;assert.throws(()=>api.command('event',{id:'toy'}));busy=false;api.command('event',{id:'toy'});assert.equal(event,'toy');
api.command('animation',{state:'walk',speed:1,paused:true});assert.equal(animation.paused,true);
assert.throws(()=>api.command('animation',{state:'bad',speed:1}));
const copy=api.snapshot();copy.care.trust=0;assert.equal(state.care.trust,100,'snapshot detached');assert(saves>0);
(async()=>{
  const storage=new Map([[content.SAVE_KEY,'original-player-progress'],[content.LEGACY_SAVE_KEY,'legacy-progress']]);
  const sandbox={window:{GameContent:{...content},DogTestTools:tools},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)}};
  vm.runInNewContext(fs.readFileSync(require('node:path').join(__dirname,'../js/admin-sandbox.js'),'utf8'),sandbox);
  const bridge=sandbox.window.GPBridge;
  assert.equal(sandbox.window.GameContent.SAVE_KEY,tools.KEY);assert.equal(sandbox.window.GameContent.LEGACY_SAVE_KEY,tools.KEY);
  await bridge.saveCloudSave({ore:5});assert.equal(JSON.parse(storage.get(tools.KEY)).ore,5);
  await bridge.wipeProgress({ore:0});await bridge.clearSaves();assert(!storage.has(tools.KEY));
  assert.equal(storage.get(content.SAVE_KEY),'original-player-progress');assert.equal(storage.get(content.LEGACY_SAVE_KEY),'legacy-progress');
  assert.equal(await bridge.loadCloudSave(),null);assert.equal(bridge.isPaymentsAvailable(),false);assert.equal(await bridge.showRewarded(),false);
  assert.equal((await bridge.purchase('anything')).success,false);
  console.log('admin: commands, limits, detached snapshots, activity guards, isolated storage, disabled cloud/payments OK');
})().catch(e=>{console.error(e);process.exitCode=1});
